### ISSUE TITLE
proposiciones_Alejandro

### ISSUE THREAD

**Issue by DanAlejandr** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-DanAlejandr#3]
[practica_proposiciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-DanAlejandr/files/13194181/practica_proposiciones.pdf)

**Comment by elisa1223** [comment]
Portada: 22%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 22%
Resultados y conclusiones: 25%

Calificación final: 18.8/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
